spring:
  application:
    name:
      backend
  data:
    mongodb:
      host: localhost
      port: 27017
      database: database
      uri: mongodb://localhost:27017/kaidan-database

jwt:
  secret: ${SECRET_KEY}
  expiration: 900000
